Repository HEXRD/hexrdgui, pull requests merged in 2021-09, with the labels that each got.

#1028 added dexela function key
  hexrd/ui/hexrd_config.py
  hexrd/ui/resources/calibration/yaml_to_gui.yml
  hexrd/ui/resources/ui/calibration_config_widget.ui
Labels: bug, enhancement

#1038 Reusable mask import export
  hexrd/ui/mask_manager_dialog.py
Labels: enhancement

#595 Hand mask in raw
  hexrd/ui/hand_drawn_mask_dialog.py
  hexrd/ui/main_window.py
  hexrd/ui/resources/ui/main_window.ui
Labels: enhancement, llnl
